Recipe:app
Shubh-Dev/recipe-application pull request #9
Opened 2022-11-10 17:40 UTC by Shubh-Dev

Hello Dear reviewer,
Because of my **partner's unavailability,** I am working solo on this group project.
I implemented almost everything as per the requirements.
Let me know if everything is alright.

2022-11-10 18:01 UTC, Lucas-Masaba requested changes
# Hello @Shubh-Dev  👋 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️ 

- Sorry that your partner was not available to do the capstone with you. Unfortunately, I cannot continue to review your pull request because as a requirement, if your partner is unavailable, you are required to attach a screenshot to your pull request from student success permitting you to work on this capstone project solo.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-11-10 18:29 UTC, DammyShittu requested changes
Hi @Shubh-Dev,

## Highlights
✔️ Descriptive PR
✔️ Passing linters
✔️ Good branch name

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-10 18:29 UTC, DammyShittu commented on config/routes.rb
>    root to: 'recipes#index'
- [ ] The food index page should be the root path. Kindly fix that.

2022-11-10 18:29 UTC, DammyShittu commented on app/views/devise/registrations/new.html.erb
> +</div>
- [ ] I get this error page when I sign up as a user. Kindly rectify it. The user is actually created but it shows this unnecessary error.

  ![nfjf](https://user-images.githubusercontent.com/54848363/201176683-2cc03517-4397-4b23-8210-77a59ea3869d.jpg)

2022-11-11 04:09 UTC, FrederickMih reviewed
Hi @Shubh-Dev, 

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request

The README.md file for this project does not have the Acknowledgment header. Also, make sure the License section has the header of [this](https://github.com/microverseinc/readme-template/edit/master/README.md) template.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-11-11 05:59 UTC, zainsadaqat approved these changes
# APPROVED!!!! 🎉 🎉 🎉 🎉 🎉 🎉
## Hey @Shubh-Dev  😊 😃 

#### Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say other than... it's time to merge it 👍🏻 ✅ 

# Congratulations!!! 🎉 🥳 👏 🙌 🎊 

<img src="https://media2.giphy.com/media/PaSnUZW1EeypulsOwd/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-11 06:01 UTC, merged